language: go
go:
  - 1.9
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mattn/goveralls
install:
  - dep ensure
script:
  - test "$TRAVIS_EVENT_TYPE" == "cron" && go test -bench=. ./infrastructure/datastore/... -run Benchmark -v -benchmem -benchtime 5s || echo "Skip benchmark"
  - goveralls -service=travis-ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  slack:
    secure: co3dPP3555iNw+riZ4Cha6YxtqToxAd5v8+gOplIm7oXq8hFBDQB+Cua09G0FfobcJ6zeZVhDoGP4iCiUyD8MJPhlyE8YAcXzzH7OTV5fg44hBeN/3ymSlTyDFWRMUoc261tBhtGEKXrhem86mHUFOAhPv7pE++FrZLWjrZxmEwYAYyTR6kBIHNScHj6DTuXHTGGuG3u6Qz1Eife8GTESU7yk+hf7mvIEm8XJbAqnS+Bq87RTIE8eHSAY0aD/pfwQtM4UBkIhwRHY9mKdmWNWW++rjlIobX2P2tgUSExY7wJyiiGY9lS1IXC/7Ks0WxzHzGUyOZezlAdjtaHVvxRxpQIgCLNlWFn2GFmc7vXofJ18p5UQ8Z1653dWOVZu+eUZD8zkFLpimdMv9mQgLVWvc7Zc1AzgG/3Cv2vHuWGc4UHeF7BxyYWLZ5oPe0LH65LWo1kKr3vGws1dsn2drTM4BMZF6bzb0Gq1xcN4ZDM+WBivEKkkERk3YjXMlCVHva0AFGjjakCknHfwSPBBtDhfKu8Pvr7aoZf9Y+1EYGElgk1rRSue4m22IXsNiVqpfWzzIhk5yrQojvRTdDDcFjytoVxfsZjVFvJtotMtLdaJRuuYMaJZxcZSiD+9R5FvuzaWx6yPGx/Ndh4dt2xdiqjnG5I5olHt19QdFjSrLg23a4=
