// Code generated by protoc-gen-go. DO NOT EDIT.
// source: photos.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	photos.proto

It has these top-level messages:
	Id
	Photo
	Empty
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Id) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Photo struct {
	Id    *Id    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *Photo) Reset()                    { *m = Photo{} }
func (m *Photo) String() string            { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()               {}
func (*Photo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Photo) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Photo) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Id)(nil), "protobuf.Id")
	proto.RegisterType((*Photo)(nil), "protobuf.Photo")
	proto.RegisterType((*Empty)(nil), "protobuf.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PhotoService service

type PhotoServiceClient interface {
	Save(ctx context.Context, in *Photo, opts ...grpc.CallOption) (*Id, error)
	Find(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Photo, error)
	Delete(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error)
}

type photoServiceClient struct {
	cc *grpc.ClientConn
}

func NewPhotoServiceClient(cc *grpc.ClientConn) PhotoServiceClient {
	return &photoServiceClient{cc}
}

func (c *photoServiceClient) Save(ctx context.Context, in *Photo, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/protobuf.PhotoService/Save", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoServiceClient) Find(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Photo, error) {
	out := new(Photo)
	err := grpc.Invoke(ctx, "/protobuf.PhotoService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoServiceClient) Delete(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/protobuf.PhotoService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PhotoService service

type PhotoServiceServer interface {
	Save(context.Context, *Photo) (*Id, error)
	Find(context.Context, *Id) (*Photo, error)
	Delete(context.Context, *Id) (*Empty, error)
}

func RegisterPhotoServiceServer(s *grpc.Server, srv PhotoServiceServer) {
	s.RegisterService(&_PhotoService_serviceDesc, srv)
}

func _PhotoService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Photo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PhotoService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).Save(ctx, req.(*Photo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PhotoService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).Find(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PhotoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoServiceServer).Delete(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhotoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.PhotoService",
	HandlerType: (*PhotoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _PhotoService_Save_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _PhotoService_Find_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PhotoService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "photos.proto",
}

func init() { proto.RegisterFile("photos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0xc8, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a,
	0x52, 0x5c, 0x4c, 0x9e, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x35, 0x17, 0x6b, 0x00, 0x48, 0x97, 0x90, 0x0c,
	0x17, 0x53, 0x66, 0x0a, 0x58, 0x8e, 0xdb, 0x88, 0x47, 0x0f, 0xa6, 0x57, 0xcf, 0x33, 0x25, 0x88,
	0x29, 0x13, 0xac, 0x39, 0x33, 0x37, 0x31, 0x3d, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08,
	0xc2, 0x51, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x34, 0xea, 0x66, 0xe4, 0xe2, 0x01,
	0x1b, 0x13, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xa4, 0xce, 0xc5, 0x12, 0x9c, 0x58, 0x96,
	0x2a, 0xc4, 0x8f, 0x30, 0x09, 0x2c, 0x2f, 0x85, 0x62, 0xb4, 0x12, 0x03, 0x48, 0xa1, 0x5b, 0x66,
	0x5e, 0x8a, 0x10, 0x8a, 0xb8, 0x14, 0xba, 0x36, 0x25, 0x06, 0x21, 0x4d, 0x2e, 0x36, 0x97, 0xd4,
	0x9c, 0xd4, 0x92, 0x54, 0xdc, 0x4a, 0xc1, 0x6e, 0x51, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x77, 0xd6, 0xe6, 0xa4, 0x10, 0x01, 0x00, 0x00,
}
